### ISSUE TITLE
BezierInterpolator should also interpolate tilt values

### ISSUE THREAD

**Issue by gonX** [AbstractQbit/AbstractOTDPlugins#1]
Some tablets report tilt values, and not smoothing these out can give some unexpected results at higher values, especially on noisy tablets.

**Comment by AbstractQbit** [comment]
Did something, does it work as you'd expect @gonX ? https://github.com/AbstractQbit/AbstractOTDPlugins/actions/runs/1558144243
Can't test it myself as win ink mode is borked on master rn, so would be nice to know if it works fine on linux at least

**Comment by gonX** [comment]
Yes, that works perfectly. I suggest hinting to the user that tilt EMA should typically be 50-100% of position EMA, though it's not important.

Closing issue since the feature is implemented. Thanks!
