### ISSUE TITLE
issue with loading the filter

### ISSUE THREAD

**Issue by JonaLK** [AbstractQbit/AbstractOTDPlugins#2]
I use OpenTabletDriver on popOS (which is Ubuntu 21.10).
Before Upgrading to 21.10, I was using 21.04 which worked fine with the plugin.
Now after installing just this plugin, I get this error:
[DllNotFoundException:Error]	Unable to load shared library 'librt' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibrt: cannot open shared object file: No such file or directory,
resulting OpenTabletDriver to show No tablet detected.

Maybe someone can help me on this.

**Comment by AbstractQbit** [comment]
Um, I don't know why that library went missing, but that's nothing that I can fix on my end. I assume you were trying to use an interpolator, OTD might depend on that library for interpolators to work. 

In any case, that's a PopOS issue, librt should come included with your system's standard C library.

**Comment by JonaLK** [comment]
I will continue to look into it, might try to reinstall all C libarys at that point.
