### ISSUE TITLE
auxiliary bindings stop functioning with bezierinterpolator enabled

### ISSUE THREAD

**Issue by inthewired** [AbstractQbit/AbstractOTDPlugins#3]
tablet auxiliary buttons (express keys) are unresponsive with bezierinterpolator enabled on intuos 4 tablet

my output: 

[Detect:Info]	Searching for tablets...
[Detect:Info]	Found tablet 'Wacom PTK-1240'
[Wacom PTK-1240:Info]	Output mode: Relative Mode
[Wacom PTK-1240:Info]	Relative Mode Sensitivity (X, Y): <10, 10>
[Wacom PTK-1240:Info]	Relative Mode Rotation: 0
[Wacom PTK-1240:Info]	Reset time: 00:00:00.0400000
[Wacom PTK-1240:Info]	Filters: BezierInterpolator.BezierInterp
[Wacom PTK-1240:Info]	Tip Binding: [Mouse Button Binding: Middle]@0%
[Wacom PTK-1240:Info]	Pen Bindings: Mouse Button Binding: Left, Mouse Button Binding: Right
[Wacom PTK-1240:Info]	Express Key Bindings: Key Binding: Escape, , , Key Binding: H, , , , , Key Binding: Application
[Settings:Info]	Driver is enabled.

plugin settings:

enabled
pre-interpolation smoothing factor: 1
tilt smoothing factor: 1
frequency: 420

**Comment by AbstractQbit** [comment]
Good catch! 
Now fixed in this release: https://github.com/AbstractQbit/AbstractOTDPlugins/releases/tag/v0.3.1
