### ISSUE TITLE
Licensing Request

### ISSUE THREAD

**Issue by elvissteinjr** [AbstractQbit/AbstractOTDPlugins#4]
Hi, this isn't exactly an issue with the plugin, but I'm not aware of other ways to contact you, so I hope you don't mind.

I'm the developer of [Desktop+](https://github.com/elvissteinjr/DesktopPlus), an open-source VR overlay application that allows access to desktops, windows and other things overlaid in VR space in SteamVR.
I've been looking into ways to implement stabilization/smoothing for shaky laser pointer inputs and found radial follow smoothing to be a nifty solution that not only works well for tablet input.

The licensing terms are clear of course. It's GPL. 
Desktop+ is also licensed under GPL, but I'm trying to keep my options open for the future and as such ask contributors to give me an exception for potential future builds to include non-free components (specifically aimed at Steamworks integration). 
Though as of now, the Steam builds I publish are the same binaries as on GitHub.

Radial follow smoothing appears to be an original concept as such (to me at least, not deep into this topic admittedly), so I would view any porting work of mine as derivative of this repo. This of course would not allow me to do non-free builds in the future.
I usually avoid GPL adding dependencies for this reason, despite using the license myself.

I suppose it's worth asking at least: 
Would it be possible for me to use it under a different license or with an exception that allows non-free binaries in the future? The app's source code would stay under GPL (minus potential glue code that prohibits being shared) and binaries free to download (Steam version is non-commercial and free). 
And for the time being it wouldn't be have non-free builds at all, but I wouldn't want to have to removing smoothing functionality in the future.

Thanks!

**Comment by AbstractQbit** [comment]
Hi, I've changed the license for the relevant file to MPL 2. You're free to make derivatives under MPL and incorporate them into a larger GPL or proprietary work as you see fit. Hope this helps.
